/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP;

public class Client extends de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.IDataStreamClientBase {
  private transient long swigCPtr;

  protected Client(long cPtr, boolean cMemoryOwn) {
    super(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Client obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.delete_ViconDataStreamSDK_CPP_Client(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Client() {
    this(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.new_ViconDataStreamSDK_CPP_Client(), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVersion GetVersion() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVersion(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetVersion(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_Connect Connect(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String HostName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_Connect(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_Connect(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(HostName), HostName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_ConnectToMulticast ConnectToMulticast(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String LocalIP, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String MulticastIP) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_ConnectToMulticast(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_ConnectToMulticast(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(LocalIP), LocalIP, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(MulticastIP), MulticastIP), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_Disconnect Disconnect() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_Disconnect(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_Disconnect(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsConnected IsConnected() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsConnected(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_IsConnected(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_StartTransmittingMulticast StartTransmittingMulticast(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String ServerIP, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String MulticastIP) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_StartTransmittingMulticast(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_StartTransmittingMulticast(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(ServerIP), ServerIP, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(MulticastIP), MulticastIP), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_StopTransmittingMulticast StopTransmittingMulticast() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_StopTransmittingMulticast(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_StopTransmittingMulticast(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableSegmentData EnableSegmentData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableSegmentData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_EnableSegmentData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableLightweightSegmentData EnableLightweightSegmentData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableLightweightSegmentData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_EnableLightweightSegmentData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableMarkerData EnableMarkerData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableMarkerData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_EnableMarkerData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableUnlabeledMarkerData EnableUnlabeledMarkerData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableUnlabeledMarkerData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_EnableUnlabeledMarkerData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableMarkerRayData EnableMarkerRayData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableMarkerRayData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_EnableMarkerRayData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableDeviceData EnableDeviceData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableDeviceData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_EnableDeviceData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableCentroidData EnableCentroidData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableCentroidData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_EnableCentroidData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableGreyscaleData EnableGreyscaleData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableGreyscaleData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_EnableGreyscaleData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableVideoData EnableVideoData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableVideoData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_EnableVideoData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableDebugData EnableDebugData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_EnableDebugData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_EnableDebugData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableSegmentData DisableSegmentData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableSegmentData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_DisableSegmentData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableLightweightSegmentData DisableLightweightSegmentData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableLightweightSegmentData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_DisableLightweightSegmentData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableMarkerData DisableMarkerData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableMarkerData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_DisableMarkerData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableUnlabeledMarkerData DisableUnlabeledMarkerData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableUnlabeledMarkerData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_DisableUnlabeledMarkerData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableMarkerRayData DisableMarkerRayData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableMarkerRayData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_DisableMarkerRayData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableDeviceData DisableDeviceData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableDeviceData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_DisableDeviceData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableCentroidData DisableCentroidData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableCentroidData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_DisableCentroidData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableGreyscaleData DisableGreyscaleData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableGreyscaleData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_DisableGreyscaleData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableVideoData DisableVideoData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableVideoData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_DisableVideoData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableDebugData DisableDebugData() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_DisableDebugData(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_DisableDebugData(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsSegmentDataEnabled IsSegmentDataEnabled() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsSegmentDataEnabled(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_IsSegmentDataEnabled(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsLightweightSegmentDataEnabled IsLightweightSegmentDataEnabled() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsLightweightSegmentDataEnabled(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_IsLightweightSegmentDataEnabled(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsMarkerDataEnabled IsMarkerDataEnabled() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsMarkerDataEnabled(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_IsMarkerDataEnabled(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsUnlabeledMarkerDataEnabled IsUnlabeledMarkerDataEnabled() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsUnlabeledMarkerDataEnabled(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_IsUnlabeledMarkerDataEnabled(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsMarkerRayDataEnabled IsMarkerRayDataEnabled() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsMarkerRayDataEnabled(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_IsMarkerRayDataEnabled(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsDeviceDataEnabled IsDeviceDataEnabled() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsDeviceDataEnabled(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_IsDeviceDataEnabled(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsCentroidDataEnabled IsCentroidDataEnabled() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsCentroidDataEnabled(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_IsCentroidDataEnabled(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsGreyscaleDataEnabled IsGreyscaleDataEnabled() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsGreyscaleDataEnabled(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_IsGreyscaleDataEnabled(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsVideoDataEnabled IsVideoDataEnabled() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsVideoDataEnabled(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_IsVideoDataEnabled(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsDebugDataEnabled IsDebugDataEnabled() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_IsDebugDataEnabled(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_IsDebugDataEnabled(swigCPtr, this), true);
  }

  public void SetBufferSize(long BufferSize) {
    de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_SetBufferSize(swigCPtr, this, BufferSize);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_SetStreamMode SetStreamMode(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.StreamMode.Enum Mode) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_SetStreamMode(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_SetStreamMode(swigCPtr, this, Mode.swigValue()), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_SetApexDeviceFeedback SetApexDeviceFeedback(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceName, boolean i_bOn) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_SetApexDeviceFeedback(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_SetApexDeviceFeedback(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceName), DeviceName, i_bOn), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_SetAxisMapping SetAxisMapping(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Direction.Enum XAxis, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Direction.Enum YAxis, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Direction.Enum ZAxis) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_SetAxisMapping(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_SetAxisMapping(swigCPtr, this, XAxis.swigValue(), YAxis.swigValue(), ZAxis.swigValue()), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetAxisMapping GetAxisMapping() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetAxisMapping(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetAxisMapping(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetServerOrientation GetServerOrientation() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetServerOrientation(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetServerOrientation(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetFrame GetFrame() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetFrame(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetFrame(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetFrameNumber GetFrameNumber() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetFrameNumber(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetFrameNumber(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetTimecode GetTimecode() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetTimecode(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetTimecode(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetFrameRate GetFrameRate() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetFrameRate(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetFrameRate(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetLatencySampleCount GetLatencySampleCount() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetLatencySampleCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetLatencySampleCount(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetLatencySampleName GetLatencySampleName(long LatencySampleIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetLatencySampleName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetLatencySampleName(swigCPtr, this, LatencySampleIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetLatencySampleValue GetLatencySampleValue(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String LatencySampleName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetLatencySampleValue(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetLatencySampleValue(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(LatencySampleName), LatencySampleName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetLatencyTotal GetLatencyTotal() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetLatencyTotal(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetLatencyTotal(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetHardwareFrameNumber GetHardwareFrameNumber() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetHardwareFrameNumber(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetHardwareFrameNumber(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetFrameRateCount GetFrameRateCount() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetFrameRateCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetFrameRateCount(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetFrameRateName GetFrameRateName(long FrameRateIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetFrameRateName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetFrameRateName(swigCPtr, this, FrameRateIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetFrameRateValue GetFrameRateValue(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String FrameRateName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetFrameRateValue(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetFrameRateValue(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(FrameRateName), FrameRateName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSubjectCount GetSubjectCount() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSubjectCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSubjectCount(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSubjectName GetSubjectName(long SubjectIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSubjectName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSubjectName(swigCPtr, this, SubjectIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSubjectRootSegmentName GetSubjectRootSegmentName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSubjectRootSegmentName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSubjectRootSegmentName(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentCount GetSegmentCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentCount(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentName GetSegmentName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, long SegmentIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentName(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, SegmentIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentChildCount GetSegmentChildCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentChildCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentChildCount(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentChildName GetSegmentChildName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName, long SegmentIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentChildName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentChildName(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName, SegmentIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentParentName GetSegmentParentName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentParentName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentParentName(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentStaticTranslation GetSegmentStaticTranslation(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentStaticTranslation(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentStaticTranslation(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentStaticRotationHelical GetSegmentStaticRotationHelical(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentStaticRotationHelical(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentStaticRotationHelical(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentStaticRotationMatrix GetSegmentStaticRotationMatrix(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentStaticRotationMatrix(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentStaticRotationMatrix(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentStaticRotationQuaternion GetSegmentStaticRotationQuaternion(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentStaticRotationQuaternion(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentStaticRotationQuaternion(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentStaticRotationEulerXYZ GetSegmentStaticRotationEulerXYZ(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentStaticRotationEulerXYZ(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentStaticRotationEulerXYZ(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentStaticScale GetSegmentStaticScale(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentStaticScale(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentStaticScale(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentGlobalTranslation GetSegmentGlobalTranslation(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentGlobalTranslation(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentGlobalTranslation(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentGlobalRotationHelical GetSegmentGlobalRotationHelical(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentGlobalRotationHelical(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentGlobalRotationHelical(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentGlobalRotationMatrix GetSegmentGlobalRotationMatrix(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentGlobalRotationMatrix(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentGlobalRotationMatrix(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentGlobalRotationQuaternion GetSegmentGlobalRotationQuaternion(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentGlobalRotationQuaternion(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentGlobalRotationQuaternion(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentGlobalRotationEulerXYZ GetSegmentGlobalRotationEulerXYZ(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentGlobalRotationEulerXYZ(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentGlobalRotationEulerXYZ(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentLocalTranslation GetSegmentLocalTranslation(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentLocalTranslation(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentLocalTranslation(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentLocalRotationHelical GetSegmentLocalRotationHelical(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentLocalRotationHelical(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentLocalRotationHelical(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentLocalRotationMatrix GetSegmentLocalRotationMatrix(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentLocalRotationMatrix(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentLocalRotationMatrix(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentLocalRotationQuaternion GetSegmentLocalRotationQuaternion(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentLocalRotationQuaternion(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentLocalRotationQuaternion(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentLocalRotationEulerXYZ GetSegmentLocalRotationEulerXYZ(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SegmentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetSegmentLocalRotationEulerXYZ(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetSegmentLocalRotationEulerXYZ(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SegmentName), SegmentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetObjectQuality GetObjectQuality(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String ObjectName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetObjectQuality(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetObjectQuality(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(ObjectName), ObjectName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetMarkerCount GetMarkerCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetMarkerCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetMarkerCount(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetMarkerName GetMarkerName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, long MarkerIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetMarkerName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetMarkerName(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, MarkerIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetMarkerParentName GetMarkerParentName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String MarkerName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetMarkerParentName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetMarkerParentName(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(MarkerName), MarkerName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetMarkerGlobalTranslation GetMarkerGlobalTranslation(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String MarkerName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetMarkerGlobalTranslation(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetMarkerGlobalTranslation(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(MarkerName), MarkerName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetMarkerRayContributionCount GetMarkerRayContributionCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String MarkerName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetMarkerRayContributionCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetMarkerRayContributionCount(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(MarkerName), MarkerName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetMarkerRayContribution GetMarkerRayContribution(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String MarkerName, long MarkerRayContributionIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetMarkerRayContribution(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetMarkerRayContribution(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(MarkerName), MarkerName, MarkerRayContributionIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetUnlabeledMarkerCount GetUnlabeledMarkerCount() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetUnlabeledMarkerCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetUnlabeledMarkerCount(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetUnlabeledMarkerGlobalTranslation GetUnlabeledMarkerGlobalTranslation(long MarkerIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetUnlabeledMarkerGlobalTranslation(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetUnlabeledMarkerGlobalTranslation(swigCPtr, this, MarkerIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetLabeledMarkerCount GetLabeledMarkerCount() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetLabeledMarkerCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetLabeledMarkerCount(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetLabeledMarkerGlobalTranslation GetLabeledMarkerGlobalTranslation(long MarkerIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetLabeledMarkerGlobalTranslation(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetLabeledMarkerGlobalTranslation(swigCPtr, this, MarkerIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceCount GetDeviceCount() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetDeviceCount(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceName GetDeviceName(long DeviceIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetDeviceName(swigCPtr, this, DeviceIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputCount GetDeviceOutputCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetDeviceOutputCount(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceName), DeviceName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputName GetDeviceOutputName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceName, long DeviceOutputIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetDeviceOutputName(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceName), DeviceName, DeviceOutputIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputComponentName GetDeviceOutputComponentName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceName, long DeviceOutputIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputComponentName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetDeviceOutputComponentName(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceName), DeviceName, DeviceOutputIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputValue GetDeviceOutputValue(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceOutputComponentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputValue(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetDeviceOutputValue__SWIG_0(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceName), DeviceName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceOutputComponentName), DeviceOutputComponentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputValue GetDeviceOutputValue(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceOutputName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceOutputComponentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputValue(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetDeviceOutputValue__SWIG_1(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceName), DeviceName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceOutputName), DeviceOutputName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceOutputComponentName), DeviceOutputComponentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputSubsamples GetDeviceOutputSubsamples(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceOutputName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputSubsamples(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetDeviceOutputSubsamples__SWIG_0(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceName), DeviceName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceOutputName), DeviceOutputName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputSubsamples GetDeviceOutputSubsamples(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceOutputName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceOutputComponentName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputSubsamples(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetDeviceOutputSubsamples__SWIG_1(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceName), DeviceName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceOutputName), DeviceOutputName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceOutputComponentName), DeviceOutputComponentName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputValue GetDeviceOutputValue(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceOutputName, long Subsample) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputValue(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetDeviceOutputValue__SWIG_2(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceName), DeviceName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceOutputName), DeviceOutputName, Subsample), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputValue GetDeviceOutputValue(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceOutputName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String DeviceOutputComponentName, long Subsample) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetDeviceOutputValue(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetDeviceOutputValue__SWIG_3(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceName), DeviceName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceOutputName), DeviceOutputName, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(DeviceOutputComponentName), DeviceOutputComponentName, Subsample), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetForcePlateCount GetForcePlateCount() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetForcePlateCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetForcePlateCount(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetGlobalForceVector GetGlobalForceVector(long ForcePlateIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetGlobalForceVector(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetGlobalForceVector__SWIG_0(swigCPtr, this, ForcePlateIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetGlobalMomentVector GetGlobalMomentVector(long ForcePlateIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetGlobalMomentVector(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetGlobalMomentVector__SWIG_0(swigCPtr, this, ForcePlateIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetGlobalCentreOfPressure GetGlobalCentreOfPressure(long ForcePlateIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetGlobalCentreOfPressure(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetGlobalCentreOfPressure__SWIG_0(swigCPtr, this, ForcePlateIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetForcePlateSubsamples GetForcePlateSubsamples(long ForcePlateIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetForcePlateSubsamples(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetForcePlateSubsamples(swigCPtr, this, ForcePlateIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetGlobalForceVector GetGlobalForceVector(long ForcePlateIndex, long Subsample) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetGlobalForceVector(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetGlobalForceVector__SWIG_1(swigCPtr, this, ForcePlateIndex, Subsample), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetGlobalMomentVector GetGlobalMomentVector(long ForcePlateIndex, long Subsample) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetGlobalMomentVector(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetGlobalMomentVector__SWIG_1(swigCPtr, this, ForcePlateIndex, Subsample), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetGlobalCentreOfPressure GetGlobalCentreOfPressure(long ForcePlateIndex, long Subsample) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetGlobalCentreOfPressure(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetGlobalCentreOfPressure__SWIG_1(swigCPtr, this, ForcePlateIndex, Subsample), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetEyeTrackerCount GetEyeTrackerCount() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetEyeTrackerCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetEyeTrackerCount(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetEyeTrackerGlobalPosition GetEyeTrackerGlobalPosition(long EyeTrackerIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetEyeTrackerGlobalPosition(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetEyeTrackerGlobalPosition(swigCPtr, this, EyeTrackerIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetEyeTrackerGlobalGazeVector GetEyeTrackerGlobalGazeVector(long EyeTrackerIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetEyeTrackerGlobalGazeVector(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetEyeTrackerGlobalGazeVector(swigCPtr, this, EyeTrackerIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCameraCount GetCameraCount() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCameraCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetCameraCount(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCameraName GetCameraName(long CameraIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCameraName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetCameraName(swigCPtr, this, CameraIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCameraId GetCameraId(String CameraName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCameraId(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetCameraId(swigCPtr, this, CameraName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCameraUserId GetCameraUserId(String CameraName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCameraUserId(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetCameraUserId(swigCPtr, this, CameraName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCameraType GetCameraType(String CameraName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCameraType(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetCameraType(swigCPtr, this, CameraName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCameraDisplayName GetCameraDisplayName(String CameraName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCameraDisplayName(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetCameraDisplayName(swigCPtr, this, CameraName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCameraResolution GetCameraResolution(String CameraName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCameraResolution(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetCameraResolution(swigCPtr, this, CameraName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetIsVideoCamera GetIsVideoCamera(String CameraName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetIsVideoCamera(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetIsVideoCamera(swigCPtr, this, CameraName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCentroidCount GetCentroidCount(String CameraName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCentroidCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetCentroidCount(swigCPtr, this, CameraName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCentroidPosition GetCentroidPosition(String CameraName, long CentroidIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCentroidPosition(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetCentroidPosition(swigCPtr, this, CameraName, CentroidIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCentroidWeight GetCentroidWeight(String CameraName, long CentroidIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetCentroidWeight(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetCentroidWeight(swigCPtr, this, CameraName, CentroidIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetGreyscaleBlobCount GetGreyscaleBlobCount(String CameraName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetGreyscaleBlobCount(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetGreyscaleBlobCount(swigCPtr, this, CameraName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetGreyscaleBlob GetGreyscaleBlob(String CameraName, long i_BlobIndex) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetGreyscaleBlob(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetGreyscaleBlob(swigCPtr, this, CameraName, i_BlobIndex), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame GetVideoFrame(String CameraName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_GetVideoFrame(swigCPtr, this, CameraName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_SetCameraFilter SetCameraFilter(SWIGTYPE_p_std__vectorT_unsigned_int_t CameraIdsForCentroids, SWIGTYPE_p_std__vectorT_unsigned_int_t CameraIdsForBlobs, SWIGTYPE_p_std__vectorT_unsigned_int_t CameraIdsForVideo) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_SetCameraFilter(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_SetCameraFilter(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(CameraIdsForCentroids), SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(CameraIdsForBlobs), SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(CameraIdsForVideo)), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_ClearSubjectFilter ClearSubjectFilter() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_ClearSubjectFilter(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_ClearSubjectFilter(swigCPtr, this), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_AddToSubjectFilter AddToSubjectFilter(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String SubjectName) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_AddToSubjectFilter(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_AddToSubjectFilter(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(SubjectName), SubjectName), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_SetTimingLogFile SetTimingLogFile(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String ClientLog, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String StreamLog) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_SetTimingLogFile(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_SetTimingLogFile(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(ClientLog), ClientLog, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(StreamLog), StreamLog), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_ConfigureWireless ConfigureWireless() {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_ConfigureWireless(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Client_ConfigureWireless(swigCPtr, this), true);
  }

}
