/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP;

public class Output_GetVideoFrame {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Output_GetVideoFrame(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Output_GetVideoFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.delete_ViconDataStreamSDK_CPP_Output_GetVideoFrame(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setResult(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Result.Enum value) {
    de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Output_GetVideoFrame_Result_set(swigCPtr, this, value.swigValue());
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Result.Enum getResult() {
    return de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Result.Enum.swigToEnum(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Output_GetVideoFrame_Result_get(swigCPtr, this));
  }

  public void setM_FrameID(long value) {
    de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Output_GetVideoFrame_m_FrameID_set(swigCPtr, this, value);
  }

  public long getM_FrameID() {
    return de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Output_GetVideoFrame_m_FrameID_get(swigCPtr, this);
  }

  public void setM_Width(int value) {
    de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Output_GetVideoFrame_m_Width_set(swigCPtr, this, value);
  }

  public int getM_Width() {
    return de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Output_GetVideoFrame_m_Width_get(swigCPtr, this);
  }

  public void setM_Height(int value) {
    de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Output_GetVideoFrame_m_Height_set(swigCPtr, this, value);
  }

  public int getM_Height() {
    return de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Output_GetVideoFrame_m_Height_get(swigCPtr, this);
  }

  public void setM_Format(long value) {
    de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Output_GetVideoFrame_m_Format_set(swigCPtr, this, value);
  }

  public long getM_Format() {
    return de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Output_GetVideoFrame_m_Format_get(swigCPtr, this);
  }

  public void setM_OffsetX(long value) {
    de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Output_GetVideoFrame_m_OffsetX_set(swigCPtr, this, value);
  }

  public long getM_OffsetX() {
    return de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Output_GetVideoFrame_m_OffsetX_get(swigCPtr, this);
  }

  public void setM_OffsetY(long value) {
    de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Output_GetVideoFrame_m_OffsetY_set(swigCPtr, this, value);
  }

  public long getM_OffsetY() {
    return de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Output_GetVideoFrame_m_OffsetY_get(swigCPtr, this);
  }

  public void setM_Data(SWIGTYPE_p_std__shared_ptrT_std__vectorT_unsigned_char_t_t value) {
    de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Output_GetVideoFrame_m_Data_set(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_std__vectorT_unsigned_char_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__shared_ptrT_std__vectorT_unsigned_char_t_t getM_Data() {
    return new SWIGTYPE_p_std__shared_ptrT_std__vectorT_unsigned_char_t_t(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_Output_GetVideoFrame_m_Data_get(swigCPtr, this), true);
  }

  public Output_GetVideoFrame() {
    this(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.new_ViconDataStreamSDK_CPP_Output_GetVideoFrame(), true);
  }

  public final static class EFormat {
    public final static de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame.EFormat ENoVideo = new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame.EFormat("ENoVideo", 0);
    public final static de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame.EFormat EMono8 = new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame.EFormat("EMono8");
    public final static de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame.EFormat EBayerRG8 = new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame.EFormat("EBayerRG8");
    public final static de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame.EFormat EBayerGB8 = new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame.EFormat("EBayerGB8");
    public final static de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame.EFormat EBayerGR8 = new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame.EFormat("EBayerGR8");
    public final static de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame.EFormat EBayerBG8 = new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame.EFormat("EBayerBG8");
    public final static de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame.EFormat ERGB888 = new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame.EFormat("ERGB888");
    public final static de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame.EFormat EBGR888 = new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.Output_GetVideoFrame.EFormat("EBGR888");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static EFormat swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + EFormat.class + " with value " + swigValue);
    }

    private EFormat(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private EFormat(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private EFormat(String swigName, EFormat swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static EFormat[] swigValues = { ENoVideo, EMono8, EBayerRG8, EBayerGB8, EBayerGR8, EBayerBG8, ERGB888, EBGR888 };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
