/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP;

public class String {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected String(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(String obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.delete_ViconDataStreamSDK_CPP_String(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String(String i_pString) {
    this(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.new_ViconDataStreamSDK_CPP_String__SWIG_0(i_pString), true);
  }

  public String() {
    this(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.new_ViconDataStreamSDK_CPP_String__SWIG_1(), true);
  }

  public String(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String i_rString) {
    this(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.new_ViconDataStreamSDK_CPP_String__SWIG_3(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(i_rString), i_rString), true);
  }

  public de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String assignmentOperator(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String i_rString) {
    return new de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String(de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_String_assignmentOperator(swigCPtr, this, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.String.getCPtr(i_rString), i_rString), false);
  }

  public void Set(String i_pString, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.IStringFactory i_rStringFactory) {
    de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_String_Set(swigCPtr, this, i_pString, de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDK.CPP.IStringFactory.getCPtr(i_rStringFactory), i_rStringFactory);
  }

  public String toStdString() {
    return de.dhbw.mobmonrob.vicon.datastreamapi.impl.ViconDataStreamSDKJNI.ViconDataStreamSDK_CPP_String_toStdString(swigCPtr, this);
  }

}
